const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Persist,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Turret,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Persistir: 0},
	{Background: 0},
	{Sólido: 0},
	{plataforma: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Senóide: 0},
	{Canhão: 0},
	{inimigo1: 0},
	{Text: 0},
	{vidas: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Sprite8: 0},
	{Mouse: 0},
	{Botão: 0},
	{Sprite9: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite10: 0},
	{vida_chefe: 0},
	{vida_subchefe: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	plataforma: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	vidas: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}